import { Link, useRoute } from "wouter";
import { ArrowLeft, Check, FileText, Heart, MessageCircle, ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export default function ProductDetail() {
  const [, params] = useRoute("/product/:sku");
  const list = trpc.catalog.list.useQuery();
  const product = (list.data ?? []).find((item: any) => item.sku === params?.sku);
  if (!product) return <main className="product-page"><Link href="/" className="back-home"><ArrowLeft size={16} /> Back to catalogue</Link><h1>Product not found</h1></main>;
  const isOem = product.authenticity === "genuine_oem";
  const whatsapp = `https://wa.me/?text=${encodeURIComponent(`Hello Lunivix, I would like to enquire about ${product.name} (${product.brand}, ${product.model}, part number ${product.sku}).`)}`;
  return <main className="product-page"><header className="inner-header"><Link href="/" className="brand-mark"><span className="brand-orb">L</span><span>Lunivix<small>Commercial supply</small></span></Link><Link href={product.productType === "equipment" ? "/equipment" : "/spare-parts"} className="back-home"><ArrowLeft size={16} /> Back to catalogue</Link></header><section className="product-detail"><div className="detail-image"><img src={product.imageUrl} alt={product.name} /><span className={isOem ? "oem-badge" : "compatible-badge"}>{isOem ? "Genuine OEM Spare Part" : product.authenticity === "compatible" ? "Compatible Replacement" : "Alternative Product"}</span></div><div className="detail-content"><span className="eyebrow plain">{product.brand} · {product.sku}</span><h1>{product.name}</h1><p className="detail-summary">{product.summary}</p><div className="detail-status"><span><Check size={16} /> {product.availability === "in_stock" ? "Available now" : product.availability === "on_order" ? "Available on order" : "Confirm availability"}</span><span><FileText size={16} /> Lead time: {product.leadTime}</span></div><div className="detail-price">{product.priceKsh === "quote" ? "Request a tailored quotation" : `KSh ${Number(product.priceKsh).toLocaleString()}`}<small>VAT status and delivery confirmed on quotation</small></div><div className="detail-actions"><Button onClick={() => toast.success("Added to your secure enquiry cart")}>{product.priceKsh === "quote" ? "Request quote" : "Add to cart"} <ShoppingBag size={16} /></Button><Button variant="outline" onClick={() => toast.success("Saved to your account shortlist")}><Heart size={16} /> Save product</Button></div><a className="whatsapp-link" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={17} /> Ask Lunivix on WhatsApp</a></div></section><section className="spec-section"><div><span className="eyebrow plain">Technical detail</span><h2>Procurement-ready<br /><em>information.</em></h2></div><div className="spec-table"><div><span>Brand</span><strong>{product.brand}</strong></div><div><span>Model</span><strong>{product.model}</strong></div><div><span>Part number / SKU</span><strong>{product.sku}</strong></div><div><span>Product classification</span><strong>{isOem ? "Genuine OEM" : product.authenticity === "compatible" ? "Compatible replacement" : "Alternative product"}</strong></div><div><span>Availability</span><strong>{product.availability.replace("_", " ")}</strong></div><div><span>Datasheet</span><strong>{product.datasheetUrl ? "Download datasheet" : "Available on request"}</strong></div></div></section></main>;
}
